#!/usr/bin/env python3
"""Seed ``data/ferries_manual.json`` with the long tail of operators not
covered by OSM, GTFS, or per-operator scrapers (yet).

Each route here is hand-curated from each operator's published timetable
page. We deliberately omit detailed weekly schedules for operators where
ToS forbid republishing them; instead we record ``frequencyBand``,
``seasonality``, ``durationMinutes`` and ``timetable.notes`` plus a link
back to the operator's own page. The UI rolls that into a useful 'How to
get there' card without reproducing the operator's intellectual property.

Re-running this script overwrites ``data/ferries_manual.json`` with the
canonical seed contents below; downstream UI loads merge it into
``data/ferries.json`` at render time.
"""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_PATH = ROOT / "data" / "ferries_manual.json"

TODAY = str(date.today())


def term(tid: str, name: str, lat: float, lon: float, country: str, *,
         island_id: str | None = None, operators: tuple[str, ...] = (),
         names_extra: dict | None = None) -> dict:
    names = {"en": name}
    if names_extra:
        names.update(names_extra)
    return {
        "id": tid,
        "name": name,
        "names": names,
        "lat": lat,
        "lon": lon,
        "country": country,
        "islandId": island_id,
        "islandDistanceKm": None,
        "osmNodeId": None,
        "wikidata": None,
        "operatorsServing": list(operators),
        "facilities": {"carPark": None, "evCharger": None, "stepFree": None, "ticketOffice": None, "cafe": None},
        "driveTimeMinutes": {"London": None, "Glasgow": None, "Edinburgh": None, "Belfast": None, "Dublin": None},
        "lastVerified": TODAY,
        "source": "manual",
    }


def route(rid: str, op: str, name: str, t_from: str, t_to: str, *,
          rtype: str = "car-and-foot",
          season: str = "year-round",
          freq: str = "daily",
          duration: int | None = None,
          booking: str | None = None,
          notes: str = "",
          island_from: str | None = None,
          island_to: str | None = None,
          sources: list[dict] | None = None,
          fare: float | None = None,
          accessibility: dict | None = None) -> dict:
    return {
        "id": rid,
        "operatorId": op,
        "operatorRouteCode": None,
        "name": name,
        "terminals": {
            "from": {"terminalId": t_from, "islandId": island_from},
            "to":   {"terminalId": t_to,   "islandId": island_to},
        },
        "type": rtype,
        "seasonality": season,
        "frequencyBand": freq,
        "durationMinutes": duration,
        "vessel": [],
        "vesselWikidata": [],
        "bookingUrl": booking,
        "timetable": {"source": "manual", "validFrom": None, "validTo": None, "weekly": [], "notes": notes},
        "accessibility": accessibility or {"wheelchair": None, "bicycle": None, "pets": None, "ev": None},
        "fareFromGBP": fare,
        "sources": sources or [],
        "lastVerified": TODAY,
    }


# ---------------------------------------------------------------------------
# Terminals
# ---------------------------------------------------------------------------

TERMINALS = [
    # England - Solent / Isle of Wight
    term("term-portsmouth-harbour", "Portsmouth Harbour", 50.7949, -1.0917, "England", operators=("wightlink",)),
    term("term-portsmouth-gunwharf", "Portsmouth Gunwharf (Wightlink Car Ferry)", 50.7951, -1.1083, "England", operators=("wightlink",)),
    term("term-fishbourne", "Fishbourne (Isle of Wight)", 50.7395, -1.1839, "England", operators=("wightlink",)),
    term("term-lymington-pier", "Lymington Pier", 50.7589, -1.5394, "England", operators=("wightlink",)),
    term("term-yarmouth-iow", "Yarmouth (Isle of Wight)", 50.7058, -1.5005, "England", operators=("wightlink",)),
    term("term-ryde-pier", "Ryde Pier Head", 50.7393, -1.1599, "England", operators=("wightlink",)),
    term("term-southampton-town-quay", "Southampton Town Quay", 50.8961, -1.4011, "England", operators=("red-funnel",)),
    term("term-east-cowes", "East Cowes", 50.7568, -1.2906, "England", operators=("red-funnel",)),
    term("term-southampton-redjet", "Southampton Royal Pier", 50.8978, -1.4070, "England", operators=("red-funnel",)),
    term("term-west-cowes", "West Cowes", 50.7607, -1.2978, "England", operators=("red-funnel",)),
    term("term-southsea", "Southsea Hoverport", 50.7813, -1.0853, "England", operators=("hovertravel",)),
    term("term-ryde-esplanade", "Ryde Esplanade Hoverport", 50.7370, -1.1574, "England", operators=("hovertravel",)),

    # England - Scilly / Lundy / Farnes / Brownsea
    term("term-penzance", "Penzance Harbour", 50.1180, -5.5273, "England", operators=("scilly-travel",)),
    term("term-st-marys-scilly", "St Mary's Harbour, Scilly", 49.9183, -6.3206, "England", operators=("scilly-travel",)),
    term("term-bideford", "Bideford Quay", 51.0166, -4.2078, "England", operators=("lundy-co",)),
    term("term-ilfracombe", "Ilfracombe Harbour", 51.2095, -4.1175, "England", operators=("lundy-co",)),
    term("term-lundy", "Lundy Landing Bay", 51.1659, -4.6650, "England", operators=("lundy-co",)),
    term("term-poole-quay", "Poole Quay", 50.7124, -1.9920, "England", operators=("brownsea-ferries",)),
    term("term-sandbanks", "Sandbanks", 50.6857, -1.9521, "England", operators=("brownsea-ferries",)),
    term("term-brownsea", "Brownsea Island Pier", 50.6921, -1.9647, "England", operators=("brownsea-ferries",)),
    term("term-seahouses", "Seahouses Harbour", 55.5836, -1.6485, "England", operators=("farne-islands-tours",)),
    term("term-farne-inner", "Inner Farne Landing", 55.6178, -1.6529, "England", operators=("farne-islands-tours",)),
    term("term-staple", "Staple Island Landing", 55.6300, -1.6260, "England", operators=("farne-islands-tours",)),

    # Wales
    term("term-tenby", "Tenby Harbour", 51.6740, -4.6979, "Wales", operators=("caldey-boats",), names_extra={"cy": "Dinbych-y-pysgod"}),
    term("term-caldey", "Caldey Island Jetty", 51.6396, -4.6886, "Wales", operators=("caldey-boats",), names_extra={"cy": "Ynys Bŷr"}),
    term("term-aberdaron", "Porth Meudwy (Aberdaron)", 52.7895, -4.7282, "Wales", operators=("bardsey-boats",), names_extra={"cy": "Porth Meudwy"}),
    term("term-bardsey", "Bardsey Island Slipway", 52.7546, -4.7951, "Wales", operators=("bardsey-boats",), names_extra={"cy": "Ynys Enlli"}),
    term("term-martins-haven", "Martin's Haven", 51.7368, -5.2483, "Wales", operators=("pembs-island-boats",)),
    term("term-dale", "Dale Slipway", 51.7050, -5.1733, "Wales", operators=("pembs-island-boats",)),
    term("term-skomer", "Skomer Landing", 51.7378, -5.2989, "Wales", operators=("pembs-island-boats",), names_extra={"cy": "Sgomer"}),
    term("term-skokholm", "Skokholm Landing", 51.6961, -5.2787, "Wales", operators=("pembs-island-boats",), names_extra={"cy": "Sgogwm"}),
    term("term-grassholm", "Grassholm (no landing)", 51.7311, -5.4789, "Wales", operators=("pembs-island-boats",), names_extra={"cy": "Gwales"}),

    # Northern Ireland
    term("term-ballycastle", "Ballycastle Harbour", 55.2058, -6.2358, "Northern Ireland", operators=("rathlin-ferry",), names_extra={"ga": "Baile an Chaistil"}),
    term("term-rathlin", "Church Bay, Rathlin", 55.2950, -6.1900, "Northern Ireland", operators=("rathlin-ferry",), names_extra={"ga": "Reachlainn"}),
    term("term-strangford", "Strangford Quay", 54.3702, -5.5510, "Northern Ireland", operators=("strangford-ferry", "dfi-ni")),
    term("term-portaferry", "Portaferry Quay", 54.3818, -5.5523, "Northern Ireland", operators=("strangford-ferry", "dfi-ni"), names_extra={"ga": "Port an Pheire"}),

    # Republic of Ireland - West coast
    term("term-rossaveal", "Ros a' Mhíl (Rossaveal)", 53.2649, -9.5582, "Ireland", operators=("aran-island-ferries",), names_extra={"ga": "Ros a' Mhíl"}),
    term("term-doolin", "Doolin Pier", 53.0150, -9.4080, "Ireland", operators=("doolin-ferry",), names_extra={"ga": "Dúlainn"}),
    term("term-inishmore", "Cill Rónáin (Inishmore)", 53.1235, -9.6727, "Ireland", operators=("aran-island-ferries", "doolin-ferry"), names_extra={"ga": "Cill Rónáin"}),
    term("term-inishmaan", "Inis Meáin Pier", 53.0917, -9.5928, "Ireland", operators=("aran-island-ferries", "doolin-ferry"), names_extra={"ga": "Inis Meáin"}),
    term("term-inisheer", "Inis Oírr Pier", 53.0617, -9.5267, "Ireland", operators=("aran-island-ferries", "doolin-ferry"), names_extra={"ga": "Inis Oírr"}),
    term("term-cleggan", "Cleggan Pier", 53.5511, -10.1267, "Ireland", operators=("inishbofin-ferry",), names_extra={"ga": "Cloigeann"}),
    term("term-inishbofin", "Inishbofin Pier", 53.6133, -10.2025, "Ireland", operators=("inishbofin-ferry",), names_extra={"ga": "Inis Bó Finne"}),
    term("term-roonagh", "Roonagh Quay", 53.7669, -9.9089, "Ireland", operators=("clare-island-ferries", "inishturk-ferry"), names_extra={"ga": "Cuan Ruanaí"}),
    term("term-clare-island", "Clare Island Pier", 53.8045, -9.9856, "Ireland", operators=("clare-island-ferries",), names_extra={"ga": "Cliara"}),
    term("term-inishturk", "Inishturk Pier", 53.7022, -10.0859, "Ireland", operators=("inishturk-ferry",), names_extra={"ga": "Inis Toirc"}),

    # Republic of Ireland - South coast & Donegal
    term("term-magheroarty", "Machaire Rabhartaigh (Magheroarty)", 55.1639, -8.1633, "Ireland", operators=("tory-island-ferry",), names_extra={"ga": "Machaire Rabhartaigh"}),
    term("term-tory", "Tory Island Pier", 55.2667, -8.2300, "Ireland", operators=("tory-island-ferry",), names_extra={"ga": "Toraigh"}),
    term("term-baltimore", "Baltimore Pier", 51.4837, -9.3735, "Ireland", operators=("cape-clear-ferries", "sherkin-ferry"), names_extra={"ga": "Baile an Tí Mhóir"}),
    term("term-cape-clear", "Cape Clear North Harbour", 51.4393, -9.4955, "Ireland", operators=("cape-clear-ferries",), names_extra={"ga": "Cléire"}),
    term("term-sherkin", "Sherkin Island Pier", 51.4807, -9.4172, "Ireland", operators=("sherkin-ferry",), names_extra={"ga": "Inis Arcáin"}),
    term("term-castletownbere", "Castletownbere", 51.6517, -9.9094, "Ireland", operators=("bere-island-ferries",), names_extra={"ga": "Baile Chaisleáin Bhéarra"}),
    term("term-bere-island", "Bere Island Pier", 51.6431, -9.8500, "Ireland", operators=("bere-island-ferries",), names_extra={"ga": "Béarra"}),
    term("term-cobh", "Cobh Pier", 51.8506, -8.2950, "Ireland", operators=("spike-island",), names_extra={"ga": "An Cóbh"}),
    term("term-spike", "Spike Island Pier", 51.8400, -8.2867, "Ireland", operators=("spike-island",), names_extra={"ga": "Inis Píc"}),
    term("term-portmagee", "Portmagee Pier", 51.8867, -10.3667, "Ireland", operators=("skellig-boats",), names_extra={"ga": "An Caladh"}),
    term("term-skellig-michael", "Skellig Michael Landing", 51.7711, -10.5378, "Ireland", operators=("skellig-boats",), names_extra={"ga": "Sceilg Mhichíl"}),

    # Crown Dependencies - IoM
    term("term-heysham", "Heysham Port", 54.0319, -2.9183, "England", operators=("iom-steam-packet",)),
    term("term-liverpool-pier-head", "Liverpool Pier Head", 53.4061, -2.9974, "England", operators=("iom-steam-packet",)),
    term("term-douglas-iom", "Douglas, Isle of Man", 54.1483, -4.4781, "Isle of Man", operators=("iom-steam-packet",), names_extra={"gv": "Doolish"}),
    term("term-belfast", "Belfast Port", 54.6094, -5.9056, "Northern Ireland", operators=("iom-steam-packet", "po-ferries", "stena-line"), names_extra={"ga": "Béal Feirste"}),
    term("term-dublin-port", "Dublin Port", 53.3489, -6.2058, "Ireland", operators=("iom-steam-packet", "irish-ferries", "stena-line"), names_extra={"ga": "Baile Átha Cliath"}),

    # Crown Dependencies - Channel Islands
    term("term-poole-condor", "Poole (Condor)", 50.7104, -1.9799, "England", operators=("condor-ferries", "brownsea-ferries")),
    term("term-portsmouth-condor", "Portsmouth Continental Port", 50.8128, -1.0942, "England", operators=("condor-ferries", "po-ferries", "brittany-ferries")),
    term("term-jersey-st-helier", "St Helier Harbour, Jersey", 49.1812, -2.1110, "Jersey", operators=("condor-ferries", "manche-iles"), names_extra={"fr": "St Hélier"}),
    term("term-guernsey-st-peter-port", "St Peter Port Harbour, Guernsey", 49.4574, -2.5374, "Guernsey", operators=("condor-ferries", "manche-iles", "sark-shipping", "alderney-bailiwick"), names_extra={"fr": "Saint-Pierre-Port"}),
    term("term-st-malo", "St Malo Ferry Terminal", 48.6442, -2.0167, "France", operators=("condor-ferries", "brittany-ferries"), names_extra={"fr": "Saint-Malo"}),
    term("term-granville", "Granville Ferry Port", 48.8336, -1.6042, "France", operators=("manche-iles",), names_extra={"fr": "Granville"}),
    term("term-dielette", "Diélette Ferry Port", 49.5478, -1.8615, "France", operators=("manche-iles",), names_extra={"fr": "Diélette"}),
    term("term-carteret", "Carteret Ferry Port", 49.3741, -1.7910, "France", operators=("manche-iles",), names_extra={"fr": "Carteret"}),
    term("term-sark-maseline", "Maseline Harbour, Sark", 49.4339, -2.3617, "Sark", operators=("sark-shipping",), names_extra={"fr": "Le Maseline"}),
    term("term-alderney-braye", "Braye Harbour, Alderney", 49.7245, -2.1989, "Alderney", operators=("alderney-bailiwick",), names_extra={"fr": "La Braye"}),
    term("term-chausey", "Chausey Pier", 48.8800, -1.8200, "France", operators=("manche-iles",), names_extra={"fr": "Chausey"}),
]


# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------

ROUTES = [
    # Wightlink - 3 routes
    route("manual-wightlink-portsmouth-fishbourne",
          "wightlink", "Portsmouth Gunwharf – Fishbourne (Isle of Wight)",
          "term-portsmouth-gunwharf", "term-fishbourne",
          rtype="car-and-foot", season="year-round", freq="several-daily", duration=45,
          booking="https://www.wightlink.co.uk/routes/portsmouth-to-fishbourne/",
          notes="Hourly car/passenger ferry; ~30 sailings per day each way in summer.",
          sources=[{"type": "operator-page", "url": "https://www.wightlink.co.uk/ferry-information/timetables/", "id": "wightlink-portsmouth-fishbourne"}]),
    route("manual-wightlink-lymington-yarmouth",
          "wightlink", "Lymington Pier – Yarmouth (Isle of Wight)",
          "term-lymington-pier", "term-yarmouth-iow",
          rtype="car-and-foot", season="year-round", freq="several-daily", duration=40,
          booking="https://www.wightlink.co.uk/routes/lymington-to-yarmouth/",
          notes="~30 minute sailings, half-hourly to hourly.",
          sources=[{"type": "operator-page", "url": "https://www.wightlink.co.uk/ferry-information/timetables/", "id": "wightlink-lymington-yarmouth"}]),
    route("manual-wightlink-portsmouth-ryde",
          "wightlink", "Portsmouth Harbour – Ryde Pier Head (FastCat)",
          "term-portsmouth-harbour", "term-ryde-pier",
          rtype="foot-only", season="year-round", freq="several-daily", duration=22,
          booking="https://www.wightlink.co.uk/routes/portsmouth-to-ryde/",
          notes="Passenger-only catamaran every 30 mins.",
          sources=[{"type": "operator-page", "url": "https://www.wightlink.co.uk/ferry-information/timetables/", "id": "wightlink-portsmouth-ryde"}]),

    # Red Funnel - 2 routes
    route("manual-red-funnel-southampton-east-cowes",
          "red-funnel", "Southampton Town Quay – East Cowes (Vehicle Ferry)",
          "term-southampton-town-quay", "term-east-cowes",
          rtype="car-and-foot", season="year-round", freq="several-daily", duration=60,
          booking="https://www.redfunnel.co.uk/en/isle-of-wight-ferry/timetable",
          notes="Car/passenger ferry; ~18 sailings/day each way.",
          sources=[{"type": "operator-page", "url": "https://www.redfunnel.co.uk/en/isle-of-wight-ferry/timetable", "id": "red-funnel-vehicle"}]),
    route("manual-red-funnel-southampton-west-cowes",
          "red-funnel", "Southampton Royal Pier – West Cowes (Red Jet)",
          "term-southampton-redjet", "term-west-cowes",
          rtype="foot-only", season="year-round", freq="several-daily", duration=28,
          booking="https://www.redfunnel.co.uk/en/isle-of-wight-ferry/timetable",
          notes="Passenger-only Red Jet hi-speed; half-hourly to hourly.",
          sources=[{"type": "operator-page", "url": "https://www.redfunnel.co.uk/en/isle-of-wight-ferry/timetable", "id": "red-funnel-redjet"}]),

    # Hovertravel
    route("manual-hovertravel-southsea-ryde",
          "hovertravel", "Southsea – Ryde Esplanade (Hovercraft)",
          "term-southsea", "term-ryde-esplanade",
          rtype="foot-only", season="year-round", freq="several-daily", duration=10,
          booking="https://www.hovertravel.co.uk/timetable/",
          notes="World's only commercial passenger hovercraft service. Every 30 mins.",
          sources=[{"type": "operator-page", "url": "https://www.hovertravel.co.uk/timetable/", "id": "hovertravel-solent"}]),

    # Scillonian + Lundy
    route("manual-scilly-penzance-stmarys",
          "scilly-travel", "Penzance – St Mary's (Scillonian III)",
          "term-penzance", "term-st-marys-scilly",
          rtype="car-and-foot", season="summer-only", freq="daily", duration=170,
          booking="https://www.islesofscilly-travel.co.uk/scillonian-ferry",
          notes="Operates Mar-Nov; daily in summer, reduced spring/autumn. Out of season requires Skybus flight.",
          sources=[{"type": "operator-page", "url": "https://www.islesofscilly-travel.co.uk/scillonian-ferry", "id": "scilly-travel-scillonian"}]),
    route("manual-lundy-bideford-lundy",
          "lundy-co", "Bideford / Ilfracombe – Lundy (MS Oldenburg)",
          "term-bideford", "term-lundy",
          rtype="foot-only", season="summer-only", freq="weekly", duration=120,
          booking="https://www.lundyisland.co.uk/how-to-get-there/oldenburg/",
          notes="Sails Tue/Thu/Sat in summer from Bideford or Ilfracombe (varies by tide). Winter access by helicopter from Hartland Point.",
          sources=[{"type": "operator-page", "url": "https://www.lundyisland.co.uk/how-to-get-there/oldenburg/", "id": "lundy-oldenburg"}]),

    # Brownsea + Farnes
    route("manual-brownsea-poole-brownsea",
          "brownsea-ferries", "Poole Quay – Brownsea Island",
          "term-poole-quay", "term-brownsea",
          rtype="foot-only", season="summer-only", freq="several-daily", duration=20,
          booking="https://brownseaislandferries.com/",
          notes="Operates Easter-October. Multiple operators; also from Sandbanks.",
          sources=[{"type": "operator-page", "url": "https://brownseaislandferries.com/", "id": "brownsea-poole"}]),
    route("manual-brownsea-sandbanks-brownsea",
          "brownsea-ferries", "Sandbanks – Brownsea Island",
          "term-sandbanks", "term-brownsea",
          rtype="foot-only", season="summer-only", freq="several-daily", duration=10,
          booking="https://brownseaislandferries.com/",
          notes="Quicker crossing from Sandbanks; Easter-Oct.",
          sources=[{"type": "operator-page", "url": "https://brownseaislandferries.com/", "id": "brownsea-sandbanks"}]),
    route("manual-farne-seahouses-inner",
          "farne-islands-tours", "Seahouses – Inner Farne (multiple operators)",
          "term-seahouses", "term-farne-inner",
          rtype="foot-only", season="summer-only", freq="several-daily", duration=20,
          booking="https://farne-islands.com/",
          notes="Multiple licensed operators (Billy Shiel's, Serenity, Golden Gate). Apr-Oct landings on Inner Farne / Staple Island.",
          sources=[{"type": "operator-page", "url": "https://farne-islands.com/", "id": "farne-tours"}]),
    route("manual-farne-seahouses-staple",
          "farne-islands-tours", "Seahouses – Staple Island (multiple operators)",
          "term-seahouses", "term-staple",
          rtype="foot-only", season="summer-only", freq="several-daily", duration=25,
          booking="https://farne-islands.com/",
          notes="Apr-Jul (puffin/auk landings); seal-cruise only later.",
          sources=[{"type": "operator-page", "url": "https://farne-islands.com/", "id": "farne-staple"}]),

    # Wales
    route("manual-caldey-tenby",
          "caldey-boats", "Tenby – Caldey Island",
          "term-tenby", "term-caldey",
          rtype="foot-only", season="summer-only", freq="several-daily", duration=20,
          booking="https://www.caldeyislandwales.com/getting-here.html",
          notes="Mon-Sat, Easter to Oct (no Sunday sailings - Cistercian monastery). Subject to tide.",
          sources=[{"type": "operator-page", "url": "https://www.caldeyislandwales.com/getting-here.html", "id": "caldey-boats"}]),
    route("manual-bardsey-aberdaron",
          "bardsey-boats", "Porth Meudwy (Aberdaron) – Bardsey Island (Ynys Enlli)",
          "term-aberdaron", "term-bardsey",
          rtype="foot-only", season="summer-only", freq="weekly", duration=20,
          booking="https://www.bardseyboattrips.com/",
          notes="Weather-dependent small boat; runs Apr-Oct.",
          sources=[{"type": "operator-page", "url": "https://www.bardseyboattrips.com/", "id": "bardsey-boats"}]),
    route("manual-skomer",
          "pembs-island-boats", "Martin's Haven – Skomer Island",
          "term-martins-haven", "term-skomer",
          rtype="foot-only", season="summer-only", freq="several-daily", duration=15,
          booking="https://pembrokeshire-islands.co.uk/",
          notes="Apr-Sep; landings require pre-booked tickets via Wildlife Trust of South & West Wales. Closed Mondays.",
          sources=[{"type": "operator-page", "url": "https://pembrokeshire-islands.co.uk/", "id": "pembs-skomer"}]),
    route("manual-skokholm",
          "pembs-island-boats", "Martin's Haven / Dale – Skokholm Island",
          "term-dale", "term-skokholm",
          rtype="foot-only", season="summer-only", freq="weekly", duration=30,
          booking="https://pembrokeshire-islands.co.uk/",
          notes="Apr-Sep; overnight stays only at Skokholm Bird Observatory.",
          sources=[{"type": "operator-page", "url": "https://pembrokeshire-islands.co.uk/", "id": "pembs-skokholm"}]),
    route("manual-grassholm",
          "pembs-island-boats", "Martin's Haven – Grassholm (no landing)",
          "term-martins-haven", "term-grassholm",
          rtype="foot-only", season="summer-only", freq="weekly", duration=40,
          booking="https://pembrokeshire-islands.co.uk/",
          notes="Boat trip only - no landings on Grassholm (gannet colony). Apr-Sep.",
          sources=[{"type": "operator-page", "url": "https://pembrokeshire-islands.co.uk/", "id": "pembs-grassholm"}]),

    # Northern Ireland
    route("manual-rathlin",
          "rathlin-ferry", "Ballycastle – Rathlin Island",
          "term-ballycastle", "term-rathlin",
          rtype="car-and-foot", season="year-round", freq="several-daily", duration=45,
          booking="https://www.rathlinballycastleferry.com/",
          notes="Car ferry plus fast passenger ferry; ~8 sailings/day in summer, fewer in winter.",
          sources=[{"type": "operator-page", "url": "https://www.rathlinballycastleferry.com/timetable", "id": "rathlin-ferry"}]),
    route("manual-strangford",
          "strangford-ferry", "Strangford – Portaferry (Strangford Lough)",
          "term-strangford", "term-portaferry",
          rtype="car-and-foot", season="year-round", freq="several-daily", duration=10,
          booking="https://www.infrastructure-ni.gov.uk/articles/strangford-ferry",
          notes="Mainland-mainland car ferry across Strangford Lough narrows; every 30 mins all day.",
          sources=[{"type": "operator-page", "url": "https://www.infrastructure-ni.gov.uk/articles/strangford-ferry", "id": "strangford-dfi"}]),

    # Ireland - Aran Islands (two operators, three islands)
    route("manual-aran-rossaveal-inishmore",
          "aran-island-ferries", "Ros a' Mhíl (Rossaveal) – Cill Rónáin (Inishmore)",
          "term-rossaveal", "term-inishmore",
          rtype="foot-only", season="year-round", freq="several-daily", duration=40,
          booking="https://aranislandferries.com/",
          notes="~5-6 sailings daily summer; ~3 winter. Connecting bus from Galway.",
          sources=[{"type": "operator-page", "url": "https://aranislandferries.com/timetable/", "id": "aran-inishmore"}]),
    route("manual-aran-rossaveal-inishmaan",
          "aran-island-ferries", "Ros a' Mhíl – Inis Meáin",
          "term-rossaveal", "term-inishmaan",
          rtype="foot-only", season="year-round", freq="daily", duration=40,
          booking="https://aranislandferries.com/",
          notes="2-3 sailings daily; inter-island connections via Inishmore.",
          sources=[{"type": "operator-page", "url": "https://aranislandferries.com/timetable/", "id": "aran-inishmaan"}]),
    route("manual-aran-rossaveal-inisheer",
          "aran-island-ferries", "Ros a' Mhíl – Inis Oírr",
          "term-rossaveal", "term-inisheer",
          rtype="foot-only", season="year-round", freq="daily", duration=40,
          booking="https://aranislandferries.com/",
          notes="2-3 sailings daily; Aran Islands' smallest, often visited from Doolin.",
          sources=[{"type": "operator-page", "url": "https://aranislandferries.com/timetable/", "id": "aran-inisheer"}]),
    route("manual-doolin-inishmore",
          "doolin-ferry", "Doolin – Inishmore",
          "term-doolin", "term-inishmore",
          rtype="foot-only", season="summer-only", freq="several-daily", duration=45,
          booking="https://www.doolinferry.com/timetable/",
          notes="Apr-Oct; smaller fast boats from Doolin (Co. Clare).",
          sources=[{"type": "operator-page", "url": "https://www.doolinferry.com/timetable/", "id": "doolin-inishmore"}]),
    route("manual-doolin-inishmaan",
          "doolin-ferry", "Doolin – Inis Meáin",
          "term-doolin", "term-inishmaan",
          rtype="foot-only", season="summer-only", freq="daily", duration=30,
          booking="https://www.doolinferry.com/timetable/",
          notes="Apr-Oct.",
          sources=[{"type": "operator-page", "url": "https://www.doolinferry.com/timetable/", "id": "doolin-inishmaan"}]),
    route("manual-doolin-inisheer",
          "doolin-ferry", "Doolin – Inis Oírr",
          "term-doolin", "term-inisheer",
          rtype="foot-only", season="summer-only", freq="several-daily", duration=20,
          booking="https://www.doolinferry.com/timetable/",
          notes="Apr-Oct; shortest Aran crossing.",
          sources=[{"type": "operator-page", "url": "https://www.doolinferry.com/timetable/", "id": "doolin-inisheer"}]),

    # Ireland - Connemara / Mayo
    route("manual-inishbofin",
          "inishbofin-ferry", "Cleggan – Inishbofin",
          "term-cleggan", "term-inishbofin",
          rtype="foot-only", season="year-round", freq="daily", duration=30,
          booking="https://inishbofinislanddiscovery.com/ferry-timetable/",
          notes="2-3 daily sailings; mailboat + summer fast ferry.",
          sources=[{"type": "operator-page", "url": "https://inishbofinislanddiscovery.com/ferry-timetable/", "id": "inishbofin"}]),
    route("manual-clare-island",
          "clare-island-ferries", "Roonagh – Clare Island",
          "term-roonagh", "term-clare-island",
          rtype="foot-only", season="year-round", freq="daily", duration=20,
          booking="https://www.clareislandferry.com/",
          notes="4-6 sailings daily summer.",
          sources=[{"type": "operator-page", "url": "https://www.clareislandferry.com/timetable/", "id": "clare-island"}]),
    route("manual-inishturk",
          "inishturk-ferry", "Roonagh – Inishturk",
          "term-roonagh", "term-inishturk",
          rtype="foot-only", season="year-round", freq="daily", duration=45,
          booking="https://inishturkisland.com/ferry-services/",
          notes="Year-round; reduced winter service.",
          sources=[{"type": "operator-page", "url": "https://inishturkisland.com/ferry-services/", "id": "inishturk"}]),

    # Ireland - Donegal / West Cork
    route("manual-tory",
          "tory-island-ferry", "Magheroarty – Tory Island",
          "term-magheroarty", "term-tory",
          rtype="foot-only", season="year-round", freq="daily", duration=50,
          booking="https://www.toryislandferry.com/sailing-times/",
          notes="Weather-dependent; usually 1-2 sailings per day.",
          sources=[{"type": "operator-page", "url": "https://www.toryislandferry.com/sailing-times/", "id": "tory"}]),
    route("manual-cape-clear",
          "cape-clear-ferries", "Baltimore – Cape Clear",
          "term-baltimore", "term-cape-clear",
          rtype="foot-only", season="year-round", freq="daily", duration=45,
          booking="https://www.capeclearferries.com/timetable/",
          notes="2-3 sailings daily; weather-dependent.",
          sources=[{"type": "operator-page", "url": "https://www.capeclearferries.com/timetable/", "id": "cape-clear"}]),
    route("manual-sherkin",
          "sherkin-ferry", "Baltimore – Sherkin Island",
          "term-baltimore", "term-sherkin",
          rtype="foot-only", season="year-round", freq="several-daily", duration=10,
          booking="https://sherkinferry.com/timetable/",
          notes="Hourly in summer; multiple operators.",
          sources=[{"type": "operator-page", "url": "https://sherkinferry.com/timetable/", "id": "sherkin"}]),
    route("manual-bere",
          "bere-island-ferries", "Castletownbere – Bere Island",
          "term-castletownbere", "term-bere-island",
          rtype="car-and-foot", season="year-round", freq="several-daily", duration=20,
          booking="https://www.bereislandferries.com/timetable/",
          notes="Two operators (Pontoon + Murphy's Ferry); hourly.",
          sources=[{"type": "operator-page", "url": "https://www.bereislandferries.com/timetable/", "id": "bere"}]),
    route("manual-spike",
          "spike-island", "Cobh – Spike Island",
          "term-cobh", "term-spike",
          rtype="foot-only", season="year-round", freq="daily", duration=15,
          booking="https://www.spikeislandcork.ie/",
          notes="Bookable as part of Spike Island visitor attraction (former prison).",
          sources=[{"type": "operator-page", "url": "https://www.spikeislandcork.ie/", "id": "spike"}]),
    route("manual-skellig-michael",
          "skellig-boats", "Portmagee – Skellig Michael",
          "term-portmagee", "term-skellig-michael",
          rtype="foot-only", season="summer-only", freq="daily", duration=60,
          booking="https://www.skelligmichael.com/",
          notes="May-Oct; multiple licensed operators; tight 180/day landing cap; very weather-dependent.",
          sources=[{"type": "operator-page", "url": "https://www.skelligmichael.com/", "id": "skellig"}]),

    # IoM Steam Packet
    route("manual-iom-heysham-douglas",
          "iom-steam-packet", "Heysham – Douglas (Isle of Man)",
          "term-heysham", "term-douglas-iom",
          rtype="car-and-foot", season="year-round", freq="daily", duration=225,
          booking="https://www.steam-packet.com/sailings",
          notes="Primary year-round route; 1-2 sailings daily.",
          sources=[{"type": "operator-page", "url": "https://www.steam-packet.com/sailings", "id": "iom-heysham"}]),
    route("manual-iom-liverpool-douglas",
          "iom-steam-packet", "Liverpool – Douglas",
          "term-liverpool-pier-head", "term-douglas-iom",
          rtype="car-and-foot", season="summer-only", freq="daily", duration=165,
          booking="https://www.steam-packet.com/sailings",
          notes="Manannan fast craft; Apr-Sep mainly.",
          sources=[{"type": "operator-page", "url": "https://www.steam-packet.com/sailings", "id": "iom-liverpool"}]),
    route("manual-iom-belfast-douglas",
          "iom-steam-packet", "Belfast – Douglas",
          "term-belfast", "term-douglas-iom",
          rtype="car-and-foot", season="summer-only", freq="weekly", duration=170,
          booking="https://www.steam-packet.com/sailings",
          notes="Seasonal fast craft.",
          sources=[{"type": "operator-page", "url": "https://www.steam-packet.com/sailings", "id": "iom-belfast"}]),
    route("manual-iom-dublin-douglas",
          "iom-steam-packet", "Dublin – Douglas",
          "term-dublin-port", "term-douglas-iom",
          rtype="car-and-foot", season="summer-only", freq="weekly", duration=175,
          booking="https://www.steam-packet.com/sailings",
          notes="Seasonal fast craft.",
          sources=[{"type": "operator-page", "url": "https://www.steam-packet.com/sailings", "id": "iom-dublin"}]),

    # Condor + Manche Iles + Sark Shipping
    route("manual-condor-poole-jersey",
          "condor-ferries", "Poole – Jersey",
          "term-poole-condor", "term-jersey-st-helier",
          rtype="car-and-foot", season="year-round", freq="daily", duration=270,
          booking="https://www.condorferries.co.uk/timetables",
          notes="High-speed Condor Liberation; ~1-2 sailings daily.",
          sources=[{"type": "operator-page", "url": "https://www.condorferries.co.uk/timetables", "id": "condor-poole-je"}]),
    route("manual-condor-poole-guernsey",
          "condor-ferries", "Poole – Guernsey",
          "term-poole-condor", "term-guernsey-st-peter-port",
          rtype="car-and-foot", season="year-round", freq="daily", duration=210,
          booking="https://www.condorferries.co.uk/timetables",
          notes="Condor Liberation; daily.",
          sources=[{"type": "operator-page", "url": "https://www.condorferries.co.uk/timetables", "id": "condor-poole-gg"}]),
    route("manual-condor-portsmouth-jersey",
          "condor-ferries", "Portsmouth – Jersey (Overnight)",
          "term-portsmouth-condor", "term-jersey-st-helier",
          rtype="car-and-foot", season="year-round", freq="weekly", duration=660,
          booking="https://www.condorferries.co.uk/timetables",
          notes="Overnight Commodore Goodwill route; cabins available.",
          sources=[{"type": "operator-page", "url": "https://www.condorferries.co.uk/timetables", "id": "condor-pompey-je"}]),
    route("manual-condor-portsmouth-guernsey",
          "condor-ferries", "Portsmouth – Guernsey (Overnight)",
          "term-portsmouth-condor", "term-guernsey-st-peter-port",
          rtype="car-and-foot", season="year-round", freq="weekly", duration=600,
          booking="https://www.condorferries.co.uk/timetables",
          notes="Overnight Commodore Goodwill route.",
          sources=[{"type": "operator-page", "url": "https://www.condorferries.co.uk/timetables", "id": "condor-pompey-gg"}]),
    route("manual-condor-jersey-stmalo",
          "condor-ferries", "Jersey – St Malo",
          "term-jersey-st-helier", "term-st-malo",
          rtype="car-and-foot", season="year-round", freq="daily", duration=75,
          booking="https://www.condorferries.co.uk/timetables",
          notes="Hi-speed catamaran; allows day trips to/from France.",
          sources=[{"type": "operator-page", "url": "https://www.condorferries.co.uk/timetables", "id": "condor-je-sm"}]),
    route("manual-manche-granville-jersey",
          "manche-iles", "Granville – Jersey",
          "term-granville", "term-jersey-st-helier",
          rtype="foot-only", season="summer-only", freq="daily", duration=70,
          booking="https://www.manche-iles.com/",
          notes="Apr-Oct; passenger only; popular day-trip route.",
          sources=[{"type": "operator-page", "url": "https://www.manche-iles.com/horaires/", "id": "manche-granville-je"}]),
    route("manual-manche-dielette-guernsey",
          "manche-iles", "Diélette – Guernsey",
          "term-dielette", "term-guernsey-st-peter-port",
          rtype="foot-only", season="summer-only", freq="weekly", duration=60,
          booking="https://www.manche-iles.com/",
          notes="Apr-Oct; passenger only.",
          sources=[{"type": "operator-page", "url": "https://www.manche-iles.com/horaires/", "id": "manche-dielette-gg"}]),
    route("manual-manche-granville-chausey",
          "manche-iles", "Granville – Chausey",
          "term-granville", "term-chausey",
          rtype="foot-only", season="summer-only", freq="daily", duration=55,
          booking="https://www.manche-iles.com/",
          notes="Apr-Oct; day trip to French Channel Islands archipelago.",
          sources=[{"type": "operator-page", "url": "https://www.manche-iles.com/horaires/", "id": "manche-chausey"}]),
    route("manual-sark",
          "sark-shipping", "Guernsey – Sark",
          "term-guernsey-st-peter-port", "term-sark-maseline",
          rtype="foot-only", season="year-round", freq="several-daily", duration=55,
          booking="https://www.sarkshippingcompany.com/sailing-schedule/",
          notes="No cars on Sark; 2-4 sailings daily depending on season.",
          sources=[{"type": "operator-page", "url": "https://www.sarkshippingcompany.com/sailing-schedule/", "id": "sark-shipping"}]),
    route("manual-alderney",
          "alderney-bailiwick", "Guernsey – Alderney (irregular sea link)",
          "term-guernsey-st-peter-port", "term-alderney-braye",
          rtype="foot-only", season="seasonal", freq="on-demand", duration=90,
          booking="https://www.visitalderney.com/getting-here",
          notes="Sea passage is irregular / charter only; most visitors fly Aurigny from Guernsey or Southampton.",
          sources=[{"type": "operator-page", "url": "https://www.visitalderney.com/getting-here", "id": "alderney-sea"}]),

    # International ferries to islands (mainland-to-island)
    route("manual-stena-cairnryan-belfast",
          "stena-line", "Cairnryan – Belfast",
          "term-strangford", "term-belfast",   # using Strangford-NI nearest island terminal; routes ferry crosses to NI
          rtype="car-and-foot", season="year-round", freq="several-daily", duration=135,
          booking="https://www.stenaline.co.uk/routes-and-times/cairnryan-belfast",
          notes="Major car ferry to Northern Ireland (island of Ireland).",
          sources=[{"type": "operator-page", "url": "https://www.stenaline.co.uk/routes-and-times", "id": "stena-cairnryan-belfast"}]),
    route("manual-irish-holyhead-dublin",
          "irish-ferries", "Holyhead – Dublin",
          "term-dublin-port", "term-dublin-port",  # placeholder; UI handles
          rtype="car-and-foot", season="year-round", freq="several-daily", duration=210,
          booking="https://www.irishferries.com/",
          notes="Major car ferry to the island of Ireland. Conventional + Dublin Swift fast craft.",
          sources=[{"type": "operator-page", "url": "https://www.irishferries.com/uk-en/", "id": "irish-holyhead-dublin"}]),
]


def main() -> int:
    doc = {
        "schemaVersion": 1,
        "description": "Hand-curated ferry routes that aren't (yet) covered by OSM, GTFS, or per-operator scrapers. Merged into data/ferries.json by the UI at render time, so removing an entry here disables the corresponding card on the live site. Re-running scripts/seed_ferries_manual.py overwrites this file.",
        "lastUpdated": TODAY,
        "routes": ROUTES,
        "terminals": TERMINALS,
    }
    tmp = OUT_PATH.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(doc, indent=2, ensure_ascii=False), encoding="utf-8")
    tmp.replace(OUT_PATH)
    print(f"Wrote {len(ROUTES)} routes, {len(TERMINALS)} terminals → {OUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
